language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: VERSION=0.3.0

before_deploy:
- GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build boilr.go  && tar czvf boilr-$VERSION-linux_amd64.tgz boilr
- GOARCH=386   GOOS=linux CGO_ENABLED=0 go build boilr.go  && tar czvf boilr-$VERSION-linux_386.tgz boilr

- GOARCH=amd64 GOOS=darwin CGO_ENABLED=0 go build boilr.go && tar czvf boilr-$VERSION-darwin_amd64.tgz boilr
- GOARCH=386   GOOS=darwin CGO_ENABLED=0 go build boilr.go && tar czvf boilr-$VERSION-darwin_386.tgz boilr

deploy:
  provider: releases
  api_key:
    secure: E0y+0V2BGbz5Va9SNQO694kAEdH5mcjrR3l8jrVDy8YUDs6SlBUDvi2QOhrhzk5+bTI+SZJfHMryh8DAN5EIqOXQ6vUepafAbvVG8nrkOyZFhI6nDhJRbg+gRR9TQqDzdpwDLb/CkvTxCGgVMIo1PMn9ev3NiJ5rKMY4NdnZehkGeBjPwwqpRyBuKT4qSIOe0IarQqNMwW1SViaQGiihEP9ajmLS+kYVZIpY5+0Hiew6PZYyD7G2SuPUTgY1up4518WKlS67jST55hJJl0PT+CQxycmlw7ZtBY7S6XtjD7I8Pi8CXNCUyoPnsp37uP7byLFHEMtiQAQF/tix110z+tzRuTViEcCQjmqaQdXacSY6+34Cf87VyYB8WouZCenSvWAiKN5Y8CI3XCF6MrsJ2CRoXCoRYtZzE+hC1blmNVgXqzC1rv0ownqhDBvM2wc/ScLHRCI5Kjoi3ovZ1q8yH/C8yQIjZjlNtKx3Au8TJiFG4s3Us1IYEmhUn9lStgykBwM4XrI+lzlOGTP5NuD1bjKq66G5C/3rqR72Lm3V7CCRQiS1+kT9KDnSgSsdRQloY2YwGo1+Ehhc6ti6tqtYauqp5sjifl4aUaoO5ysaktj/mEYSK1qbQ1xY0YL7ZNz/TeMGpcPg0Zu1xvizEmnJGUarL01hxkSQSbFk6cqjBT4=
  file:
    - install
    - boilr-$VERSION-darwin_386.tgz
    - boilr-$VERSION-darwin_amd64.tgz
    - boilr-$VERSION-linux_386.tgz
    - boilr-$VERSION-linux_amd64.tgz
  skip_cleanup: true
  on:
    repo: tmrts/boilr
    branch: master
    tags: true
